[build]
  command = "npm run build" # Command to build your React app
  publish = "build"         # Directory to publish after the build

# Optional: Redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Optional: Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
